version: '3.8'

services:
  paste:
    image: danielszabo99/microbin
    restart: always
    ports:
      - "8065:8080"
    volumes:
      - /docker/microbin:/my/microbin
      - /docker/microbin/data:/app/pasta_data
