version: '3.6'

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    user: "0:0"
    group_add:
      - "996"
    volumes:
      - ${FLAME_DATA_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    restart: unless-stopped