version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data  # bind mount für persistente Daten
    restart: unless-stopped
    networks:
      - node-red-net

networks:
  node-red-net:
