version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    user: "1000:1000"
    environment:
      - TZ=${TZ}
    ports:
      - "1880:1880"
    volumes:
      - ${NODE_RED_DATA}:/data
    restart: unless-stopped
    networks:
      - node-red-net

networks:
  node-red-net:
