version: '3.3'
services:
    it-tools:
        container_name: it-tools
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            - UID=1000
            - GID=1000
        image: 'corentinth/it-tools:latest' 